export { default as Bishop } from './Bishop'
export { default as King } from './King'
export { default as Knight } from './Knight'
export { default as Pawn } from './Pawn'
export { default as Queen } from './Queen'
export { default as Rook } from './Rook'
